# RV32 面试最终预设，2026-10-02 经用户确认采用。命令行覆盖后视为新实验。
# I-cache：docs/verification/ICACHE_SELECTION_2026-09-21.md
# 分支预测：docs/research/branch-v3/decision.md，H2E-victim。
# BHT16/BTB16两路/RAS4，弱态BTFNT及I-cache返回后的直接目标计算。
# 当前测量：整核面积102004.882 um^2，NanGate45/AREA3综合后STA通过700 MHz；
# 阵列旁路简化见 docs/verification/RV32_WAIT_OPT_2026-10-02.md；运行默认仍为700 MHz。
# 非布局布线签核。映射目标820 MHz与运行频率分开。
NPC_ICACHE_CAPACITY_BYTES      ?= 1024
NPC_ICACHE_WAY_COUNT           ?= 4
NPC_ICACHE_LINE_BYTES          ?= 32
NPC_ICACHE_REPLACEMENT_POLICY  ?= 13
NPC_DCACHE_ENABLE             ?= 1
NPC_DCACHE_CAPACITY_BYTES     ?= 256
NPC_DCACHE_WAY_COUNT          ?= 2
NPC_DCACHE_LINE_BYTES         ?= 16
NPC_BRANCH_HISTORY_ENTRY_COUNT ?= 16
NPC_BRANCH_TARGET_ENTRY_COUNT  ?= 16
NPC_BRANCH_TARGET_WAY_COUNT    ?= 2
NPC_BRANCH_TARGET_WAY_BITS     ?= 0
NPC_BRANCH_TARGET_POLICY       ?= 0
NPC_BRANCH_DIRECTION_POLICY    ?= 0
NPC_BRANCH_GLOBAL_HISTORY_BITS ?= 4
NPC_RETURN_STACK_ENTRY_COUNT   ?= 4
NPC_SDRAM_NATIVE_READ_BURST     ?= 1
NPC_SIM_CPU_FREQ_MHZ            ?= 700

# 只启用冻结的均衡组合，其他方向保持显式实验开关。
NPC_BRANCH_STATIC_POLICY          ?= 2
NPC_BRANCH_EARLY_TARGET           ?= 1
NPC_BRANCH_TARGET_INDEX_POLICY    ?= 0
NPC_BRANCH_TARGET_ADMISSION_POLICY ?= 0
NPC_BRANCH_EARLY_RAS              ?= 0
NPC_BRANCH_SPEC_HISTORY           ?= 0
NPC_BRANCH_SC_ENABLE              ?= 0
NPC_BRANCH_LOOP_ENABLE            ?= 0
