# RV32 面试稳定预设，2026-09-24 固定。命令行覆盖后视为新实验。
# 结构选择：docs/verification/ICACHE_SELECTION_2026-09-21.md
# 预测器选择：docs/verification/BRANCH_HISTORY_EXPLORATION_2026-09-24.md
# 当前源码关闭实验机制（B0I）：整核含复位边界 101418.618 um^2，
# NanGate45 综合后完整 STA 通过 720 MHz；不是布局布线后频率。
# 映射仍使用统一 AREA3 / 820 MHz 目标，不由仿真频率替代。
NPC_ICACHE_CAPACITY_BYTES      ?= 1024
NPC_ICACHE_WAY_COUNT           ?= 4
NPC_ICACHE_LINE_BYTES          ?= 32
NPC_ICACHE_REPLACEMENT_POLICY  ?= 13
NPC_DCACHE_ENABLE             ?= 1
NPC_DCACHE_CAPACITY_BYTES     ?= 256
NPC_DCACHE_WAY_COUNT          ?= 2
NPC_DCACHE_LINE_BYTES         ?= 16
NPC_BRANCH_HISTORY_ENTRY_COUNT ?= 16
NPC_BRANCH_TARGET_ENTRY_COUNT  ?= 16
NPC_BRANCH_TARGET_WAY_COUNT    ?= 2
NPC_BRANCH_TARGET_WAY_BITS     ?= 0
NPC_BRANCH_TARGET_POLICY       ?= 0
NPC_BRANCH_DIRECTION_POLICY    ?= 0
NPC_BRANCH_GLOBAL_HISTORY_BITS ?= 4
NPC_RETURN_STACK_ENTRY_COUNT   ?= 4
NPC_SDRAM_NATIVE_READ_BURST     ?= 1
NPC_SIM_CPU_FREQ_MHZ            ?= 720
