${NPC_HOME}/vsrc/riscv32/common/riscv32_pkg.sv
${NPC_HOME}/vsrc/riscv32/core/riscv32_arch_regfile.sv
${NPC_HOME}/vsrc/riscv32/core/riscv32_csr_file.sv
${NPC_HOME}/vsrc/riscv32/core/riscv32_idu.sv
${NPC_HOME}/vsrc/riscv32/core/riscv32_exu.sv
${NPC_HOME}/vsrc/riscv32/core/riscv32_lsu.sv
${NPC_HOME}/vsrc/riscv32/core/riscv32_completion_mux.sv
${NPC_HOME}/vsrc/riscv32/core/riscv32_commit.sv
${NPC_HOME}/vsrc/riscv32/core/riscv32_trap_controller.sv
${NPC_HOME}/vsrc/riscv32/core/riscv32_redirect_arbiter.sv
${NPC_HOME}/vsrc/riscv32/core/riscv32_ifu.sv
${NPC_HOME}/vsrc/riscv32/core/riscv32_core.sv
${NPC_HOME}/vsrc/riscv32/system/riscv32_axi_lite_arbiter.sv
${NPC_HOME}/vsrc/riscv32/system/riscv32_axi_lite_xbar.sv
${NPC_HOME}/vsrc/riscv32/system/peripheral/riscv32_axi_lite_clint.sv
${NPC_HOME}/vsrc/riscv32/system/riscv32_npc_axi_core_boundary.sv
${NPC_HOME}/vsrc/riscv32/system/riscv32_npc_axi.sv
