#!/usr/bin/env python3
"""Native timer regression for target storage; deliberately runs test, never train."""
import argparse
import json
from pathlib import Path
import subprocess
from compact_target_artifacts import prune_objects
from explore_frontend import sha


def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--root',type=Path,required=True)
    a=p.parse_args();root=a.root.resolve();configs=json.loads((root/'configurations.json').read_text())
    common=min(json.loads(p.read_text())['mhz'] for p in (root/'ppa').glob('*/qualified.json'))
    records=[];image_hash=None
    for name in ['B0off','F16','U16','H32']:
        cfg=configs[name];folder=root/'microbench'/name
        command=['python3','npc/scripts/run_microbench_perf.py','--scale','test','--cpu-mhz',str(common),
            '--icache-bytes','1024','--icache-ways','4','--icache-line','32','--icache-policy','13',
            '--bht-entries','16','--btb-entries',str(cfg['btb']),'--btb-ways',str(cfg['ways']),
            '--btb-policy','0','--ras-entries','4','--host-opt','2','--verify-observer','--output',str(folder)]
        if cfg['widths']:command+=['--btb-target-bits',*map(str,cfg['widths'])]
        folder.parent.mkdir(exist_ok=True)
        if not (folder/'report.json').exists():
            with (folder.parent/(name+'-driver.log')).open('x') as log:
                subprocess.run(command,stdout=log,stderr=subprocess.STDOUT,check=True)
        report=json.loads((folder/'report.json').read_text());manifest=json.loads((folder/'manifest.json').read_text())
        assert report['status']=='passed' and report['observer_on_off_verified']
        assert report['cpu_mhz']==common and report['scale']=='test'
        assert manifest['predictor']['target_bits']==cfg['widths']
        current=sha(folder/'microbench.bin')
        if image_hash is None:image_hash=current
        assert current==image_hash
        records.append({'name':name,'command':command,'report_sha256':sha(folder/'report.json')})
        # These exact clock/width build tags were first generated by this study.
        build=Path(next(x.split('=',1)[1] for x in manifest['build_command'] if x.startswith('BUILD_DIR=')))
        removed=prune_objects(build)
        (folder/'compiler-cache-cleanup.json').write_text(json.dumps(removed,indent=2)+'\n')
        print('PASS native timer',name,report['total']['timer_seconds'],flush=True)
    (root/'microbench-complete.json').write_text(json.dumps({'status':'passed','common_mhz':common,
        'scale':'test','image_sha256':image_hash,'records':records,'train_rerun':False},indent=2)+'\n')


if __name__=='__main__':main()
